import array
array1 = array.array('i', [1, 2, 3, 4, 5])
print(type(array1))
array1.append(6)
print(array1)
array1.insert(0, 0)
print(array1)
array1.remove(3)
print(array1)
array1.pop()
print(array1)
array1.reverse()
print(array1)
array1.extend([7, 8, 9])
print(array1)